/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVESRPC_H_RPCGEN
#define _CLAVESRPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct PaqueteRPC {
	int x;
	int y;
	int z;
};
typedef struct PaqueteRPC PaqueteRPC;

struct SetModArgs {
	char *key;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		float *V_value2_val;
	} V_value2;
	PaqueteRPC value3;
};
typedef struct SetModArgs SetModArgs;

struct GetResult {
	int resultado;
	char *value1;
	int N_value2;
	struct {
		u_int V_value2_len;
		float *V_value2_val;
	} V_value2;
	PaqueteRPC value3;
};
typedef struct GetResult GetResult;

#define CLAVES_PROG 0x20001234
#define CLAVES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define destroy_rpc 1
extern  enum clnt_stat destroy_rpc_1(int *, CLIENT *);
extern  bool_t destroy_rpc_1_svc(int *, struct svc_req *);
#define set_rpc 2
extern  enum clnt_stat set_rpc_1(SetModArgs , int *, CLIENT *);
extern  bool_t set_rpc_1_svc(SetModArgs , int *, struct svc_req *);
#define get_rpc 3
extern  enum clnt_stat get_rpc_1(char *, GetResult *, CLIENT *);
extern  bool_t get_rpc_1_svc(char *, GetResult *, struct svc_req *);
#define modify_rpc 4
extern  enum clnt_stat modify_rpc_1(SetModArgs , int *, CLIENT *);
extern  bool_t modify_rpc_1_svc(SetModArgs , int *, struct svc_req *);
#define delete_rpc 5
extern  enum clnt_stat delete_rpc_1(char *, int *, CLIENT *);
extern  bool_t delete_rpc_1_svc(char *, int *, struct svc_req *);
#define exist_rpc 6
extern  enum clnt_stat exist_rpc_1(char *, int *, CLIENT *);
extern  bool_t exist_rpc_1_svc(char *, int *, struct svc_req *);
extern int claves_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define destroy_rpc 1
extern  enum clnt_stat destroy_rpc_1();
extern  bool_t destroy_rpc_1_svc();
#define set_rpc 2
extern  enum clnt_stat set_rpc_1();
extern  bool_t set_rpc_1_svc();
#define get_rpc 3
extern  enum clnt_stat get_rpc_1();
extern  bool_t get_rpc_1_svc();
#define modify_rpc 4
extern  enum clnt_stat modify_rpc_1();
extern  bool_t modify_rpc_1_svc();
#define delete_rpc 5
extern  enum clnt_stat delete_rpc_1();
extern  bool_t delete_rpc_1_svc();
#define exist_rpc 6
extern  enum clnt_stat exist_rpc_1();
extern  bool_t exist_rpc_1_svc();
extern int claves_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PaqueteRPC (XDR *, PaqueteRPC*);
extern  bool_t xdr_SetModArgs (XDR *, SetModArgs*);
extern  bool_t xdr_GetResult (XDR *, GetResult*);

#else /* K&R C */
extern bool_t xdr_PaqueteRPC ();
extern bool_t xdr_SetModArgs ();
extern bool_t xdr_GetResult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVESRPC_H_RPCGEN */
