/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "clavesRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
destroy_rpc_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, destroy_rpc, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
set_rpc_1(SetModArgs arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, set_rpc,
		(xdrproc_t) xdr_SetModArgs, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_rpc_1(char *arg1, GetResult *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, get_rpc,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_GetResult, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modify_rpc_1(SetModArgs arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, modify_rpc,
		(xdrproc_t) xdr_SetModArgs, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_rpc_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, delete_rpc,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_rpc_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, exist_rpc,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
