/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_PaqueteRPC (XDR *xdrs, PaqueteRPC *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SetModArgs (XDR *xdrs, SetModArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->key, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_PaqueteRPC (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GetResult (XDR *xdrs, GetResult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->resultado))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->V_value2.V_value2_val, (u_int *) &objp->V_value2.V_value2_len, 32,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_PaqueteRPC (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
